version: '3.1'

services:

  mysql:
    container_name: harvestHub-mysql
    image: mysql:8.0.32
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: harvestHub
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      description: "O serviço MySQL para o aplicativo harvestHub"
      version: "8.0.32"